<a href="https://colab.research.google.com/github/nikeshgamal24/LSTM-Project/blob/main/GRU_Practical_Implementation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Data Collection And Data Processing

In [38]:
## Data Collection
import nltk
nltk.download('gutenberg')

from nltk.corpus import gutenberg
import pandas as pd

[nltk_data] Downloading package gutenberg to /root/nltk_data...
[nltk_data]   Package gutenberg is already up-to-date!


In [39]:
## load the dataset
data =gutenberg.raw('shakespeare-hamlet.txt')

## save to a file
with open('hamlet.txt','w') as file:
  file.write(data)

In [40]:
## Data Preprocessing
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.model_selection import train_test_split

In [41]:
## lad the dataset
with open('hamlet.txt','r') as file:
  text = file.read().lower()

In [42]:
text

"[the tragedie of hamlet by william shakespeare 1599]\n\n\nactus primus. scoena prima.\n\nenter barnardo and francisco two centinels.\n\n  barnardo. who's there?\n  fran. nay answer me: stand & vnfold\nyour selfe\n\n   bar. long liue the king\n\n   fran. barnardo?\n  bar. he\n\n   fran. you come most carefully vpon your houre\n\n   bar. 'tis now strook twelue, get thee to bed francisco\n\n   fran. for this releefe much thankes: 'tis bitter cold,\nand i am sicke at heart\n\n   barn. haue you had quiet guard?\n  fran. not a mouse stirring\n\n   barn. well, goodnight. if you do meet horatio and\nmarcellus, the riuals of my watch, bid them make hast.\nenter horatio and marcellus.\n\n  fran. i thinke i heare them. stand: who's there?\n  hor. friends to this ground\n\n   mar. and leige-men to the dane\n\n   fran. giue you good night\n\n   mar. o farwel honest soldier, who hath relieu'd you?\n  fra. barnardo ha's my place: giue you goodnight.\n\nexit fran.\n\n  mar. holla barnardo\n\n   bar. 

In [43]:
## tokenize the text - creating indexes for words
tokenizer = Tokenizer()
tokenizer.fit_on_texts([text])

In [44]:
tokenizer.word_index

{'the': 1,
 'and': 2,
 'to': 3,
 'of': 4,
 'i': 5,
 'you': 6,
 'a': 7,
 'my': 8,
 'it': 9,
 'in': 10,
 'that': 11,
 'ham': 12,
 'is': 13,
 'not': 14,
 'his': 15,
 'this': 16,
 'with': 17,
 'your': 18,
 'but': 19,
 'for': 20,
 'me': 21,
 'lord': 22,
 'as': 23,
 'what': 24,
 'he': 25,
 'be': 26,
 'so': 27,
 'him': 28,
 'haue': 29,
 'king': 30,
 'will': 31,
 'no': 32,
 'our': 33,
 'we': 34,
 'on': 35,
 'are': 36,
 'if': 37,
 'all': 38,
 'then': 39,
 'shall': 40,
 'by': 41,
 'thou': 42,
 'come': 43,
 'or': 44,
 'hamlet': 45,
 'good': 46,
 'do': 47,
 'hor': 48,
 'her': 49,
 'let': 50,
 'now': 51,
 'thy': 52,
 'how': 53,
 'more': 54,
 'they': 55,
 'from': 56,
 'enter': 57,
 'at': 58,
 'was': 59,
 'oh': 60,
 'like': 61,
 'most': 62,
 'there': 63,
 'well': 64,
 'know': 65,
 'selfe': 66,
 'would': 67,
 'them': 68,
 'loue': 69,
 'may': 70,
 "'tis": 71,
 'vs': 72,
 'sir': 73,
 'qu': 74,
 'which': 75,
 'did': 76,
 'why': 77,
 'laer': 78,
 'giue': 79,
 'thee': 80,
 'ile': 81,
 'must': 82,
 'hath': 

In [45]:
total_words = len(tokenizer.word_index)+1

In [46]:
total_words

4818

In [47]:
## create input sequences:
input_sequences = []
for line in text.split('\n'):
  print(f"tokenizer.texts_to_sequences([line])[0]:{tokenizer.texts_to_sequences([line])[0]}")
  token_list = tokenizer.texts_to_sequences([line])[0]

  for i in range(1,len(token_list)):
    n_gram_sequence = token_list[:i+1]
    print(f'n_gram_sequence: {n_gram_sequence}')
    input_sequences.append(n_gram_sequence)

tokenizer.texts_to_sequences([line])[0]:[1, 687, 4, 45, 41, 1886, 1887, 1888]
n_gram_sequence: [1, 687]
n_gram_sequence: [1, 687, 4]
n_gram_sequence: [1, 687, 4, 45]
n_gram_sequence: [1, 687, 4, 45, 41]
n_gram_sequence: [1, 687, 4, 45, 41, 1886]
n_gram_sequence: [1, 687, 4, 45, 41, 1886, 1887]
n_gram_sequence: [1, 687, 4, 45, 41, 1886, 1887, 1888]
tokenizer.texts_to_sequences([line])[0]:[]
tokenizer.texts_to_sequences([line])[0]:[]
tokenizer.texts_to_sequences([line])[0]:[1180, 1889, 1890, 1891]
n_gram_sequence: [1180, 1889]
n_gram_sequence: [1180, 1889, 1890]
n_gram_sequence: [1180, 1889, 1890, 1891]
tokenizer.texts_to_sequences([line])[0]:[]
tokenizer.texts_to_sequences([line])[0]:[57, 407, 2, 1181, 177, 1892]
n_gram_sequence: [57, 407]
n_gram_sequence: [57, 407, 2]
n_gram_sequence: [57, 407, 2, 1181]
n_gram_sequence: [57, 407, 2, 1181, 177]
n_gram_sequence: [57, 407, 2, 1181, 177, 1892]
tokenizer.texts_to_sequences([line])[0]:[]
tokenizer.texts_to_sequences([line])[0]:[407, 1182, 63

In [48]:
input_sequences

[[1, 687],
 [1, 687, 4],
 [1, 687, 4, 45],
 [1, 687, 4, 45, 41],
 [1, 687, 4, 45, 41, 1886],
 [1, 687, 4, 45, 41, 1886, 1887],
 [1, 687, 4, 45, 41, 1886, 1887, 1888],
 [1180, 1889],
 [1180, 1889, 1890],
 [1180, 1889, 1890, 1891],
 [57, 407],
 [57, 407, 2],
 [57, 407, 2, 1181],
 [57, 407, 2, 1181, 177],
 [57, 407, 2, 1181, 177, 1892],
 [407, 1182],
 [407, 1182, 63],
 [408, 162],
 [408, 162, 377],
 [408, 162, 377, 21],
 [408, 162, 377, 21, 247],
 [408, 162, 377, 21, 247, 882],
 [18, 66],
 [451, 224],
 [451, 224, 248],
 [451, 224, 248, 1],
 [451, 224, 248, 1, 30],
 [408, 407],
 [451, 25],
 [408, 6],
 [408, 6, 43],
 [408, 6, 43, 62],
 [408, 6, 43, 62, 1893],
 [408, 6, 43, 62, 1893, 96],
 [408, 6, 43, 62, 1893, 96, 18],
 [408, 6, 43, 62, 1893, 96, 18, 566],
 [451, 71],
 [451, 71, 51],
 [451, 71, 51, 1894],
 [451, 71, 51, 1894, 567],
 [451, 71, 51, 1894, 567, 378],
 [451, 71, 51, 1894, 567, 378, 80],
 [451, 71, 51, 1894, 567, 378, 80, 3],
 [451, 71, 51, 1894, 567, 378, 80, 3, 273],
 [451, 71

In [49]:
## Pad Sequence - to make the dimension uniform
max_sequence_len = max([len(x) for x in input_sequences])
max_sequence_len

14

In [50]:
input_sequences = np.array(pad_sequences(input_sequences,maxlen=max_sequence_len,padding='pre'))
input_sequences

array([[   0,    0,    0, ...,    0,    1,  687],
       [   0,    0,    0, ...,    1,  687,    4],
       [   0,    0,    0, ...,  687,    4,   45],
       ...,
       [   0,    0,    0, ...,    4,   45, 1047],
       [   0,    0,    0, ...,   45, 1047,    4],
       [   0,    0,    0, ..., 1047,    4,  193]], dtype=int32)

In [51]:
## Create prediction and label
import tensorflow as tf
x,y = input_sequences[:,:-1], input_sequences[:,-1]

In [52]:
x

array([[   0,    0,    0, ...,    0,    0,    1],
       [   0,    0,    0, ...,    0,    1,  687],
       [   0,    0,    0, ...,    1,  687,    4],
       ...,
       [   0,    0,    0, ...,  687,    4,   45],
       [   0,    0,    0, ...,    4,   45, 1047],
       [   0,    0,    0, ...,   45, 1047,    4]], dtype=int32)

In [53]:
y

array([ 687,    4,   45, ..., 1047,    4,  193], dtype=int32)

In [54]:
## for output --> convert it into the categories
y = tf.keras.utils.to_categorical(y,num_classes=total_words)
y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [55]:
## Split the data into training and testing sets
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

In [56]:
## train our GRU RNN
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM,Dense, Dropout,GRU

In [57]:
## Define the model
model = Sequential()
model.add(Embedding(total_words,100,input_length= max_sequence_len-1))
model.add(GRU(150,return_sequences=True))
model.add(Dropout(0.2))
model.add(GRU(100))
model.add(Dense(total_words,activation='softmax'))

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [58]:
## compile the model
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ gru (GRU)                       │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ ?                      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ gru_1 (GRU)                     │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [59]:
## Train the model
history = model.fit(x_train,y_train,epochs=100,validation_data=(x_test,y_test),verbose = 1)

Epoch 1/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 43s 60ms/step - accuracy: 0.0292 - loss: 7.1976 - val_accuracy: 0.0385 - val_loss: 6.7920
Epoch 2/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 39s 57ms/step - accuracy: 0.0373 - loss: 6.4575 - val_accuracy: 0.0503 - val_loss: 6.7971
Epoch 3/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 38s 58ms/step - accuracy: 0.0509 - loss: 6.1899 - val_accuracy: 0.0663 - val_loss: 6.7782
Epoch 4/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 41s 58ms/step - accuracy: 0.0755 - loss: 5.8404 - val_accuracy: 0.0756 - val_loss: 6.8056
Epoch 5/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 42s 60ms/step - accuracy: 0.0920 - loss: 5.5148 - val_accuracy: 0.0736 - val_loss: 6.8863
Epoch 6/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 40s 58ms/step - accuracy: 0.1017 - loss: 5.2241 - val_accuracy: 0.0775 - val_loss: 6.9937
Epoch 7/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 40s 57ms/step - accuracy: 0.1117 - loss: 4.9784 - val_accuracy: 0.0754 - val_loss: 7.0586
Epoch 8/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 41s 58ms/step - accuracy: 0.1374 - loss: 4

In [64]:
## function to predict the next word
def predict_next_word(model,tokenizer,text,max_sequence_len):
  token_list = tokenizer.texts_to_sequences([text])[0]

  if len(token_list) >= max_sequence_len:
    token_list = token_list[-(max_sequence_len-1):]

  token_list = pad_sequences([token_list],maxlen=max_sequence_len-1,padding='pre')
  predicted = model.predict(token_list,verbose=0)

  predicted_word_index = np.argmax(predicted,axis=1)

  for word,index in tokenizer.word_index.items():
    if index == predicted_word_index:
      return word
  return None

In [65]:
input_text = "To be or not to be"
print(f"Input Text: {input_text}")

max_sequence_len = model.input_shape[1]+1
next_word = predict_next_word(model,tokenizer,input_text,max_sequence_len)
print(f"Next Word Prediction: {next_word}")

Input Text: To be or not to be
Next Word Prediction: his


In [66]:
## save the model
model.save("next_word_gru.h5")

In [67]:
## save the tokenizer
import pickle
with open('tokenizer_gru.pickle','wb') as handle:
  pickle.dump(tokenizer,handle,protocol = pickle.HIGHEST_PROTOCOL)